#!/usr/bin/env python3
from argparse import ArgumentParser
import commands


all_commands = list(map(commands.__dict__.get, commands.__all__))


def main():
    parser = ArgumentParser(description="advent of code 2022 command-line interface")

    subparsers = parser.add_subparsers()
    for command_cls in all_commands:
        command = command_cls()
        subparser = subparsers.add_parser(
            command.name, prog=command.name, description=command.description
        )
        command.add_arguments(subparser)
        subparser.set_defaults(exec=command.exec)

    args = vars(parser.parse_args())
    exec = args.pop("exec", None)
    if not exec:
        parser.print_help()
        return

    exec(**args)


if __name__ == "__main__":
    main()
