#!/usr/bin/env python3
from argparse import ArgumentParser
from commands import GenCommand, RunCommand


commands = [GenCommand, RunCommand]


def main():
    parser = ArgumentParser(
        prog="cli", description="Advent of Code 2022 command-line interface"
    )

    subparsers = parser.add_subparsers()
    for command_cls in commands:
        command = command_cls()
        subparser = subparsers.add_parser(command.name)
        command.add_arguments(subparser)
        subparser.set_defaults(exec=command.exec)

    args = vars(parser.parse_args())
    exec = args.pop("exec", None)
    if not exec:
        parser.print_help()
        return

    exec(**args)


if __name__ == "__main__":
    main()
