#!/usr/bin/env python3
from argparse import ArgumentParser
from commands import gen, run


def main():
    parser = ArgumentParser(
        prog="cli", description="Advent of Code 2022 command-line interface"
    )

    subparsers = parser.add_subparsers()

    gen_parser = subparsers.add_parser("gen")
    gen_parser.add_argument(
        "day", type=int, choices=range(1, 26), help="The day to generate"
    )
    gen_parser.set_defaults(exec=gen.command)

    run_parser = subparsers.add_parser("run")
    run_parser.add_argument(
        "day",
        type=int,
        nargs="?",
        choices=range(1, 26),
        default=0,
        help="The day to run",
    )
    run_parser.add_argument(
        "part",
        type=int,
        nargs="?",
        choices=(
            1,
            2,
        ),
        default=0,
        help="The part to run",
    )
    run_parser.set_defaults(exec=run.command)

    args = vars(parser.parse_args())
    exec = args.pop("exec", None)
    if not exec:
        parser.print_help()
        return

    exec(**args)


if __name__ == "__main__":
    main()
